# Generated by Django 4.1.1 on 2022-09-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('genero', models.CharField(max_length=128)),
                ('fecha', models.DateField()),
                ('aptoPara', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('genero', models.CharField(max_length=128)),
                ('fecha', models.DateField()),
                ('aptoPara', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('genero', models.CharField(max_length=128)),
                ('fecha', models.DateField()),
                ('aptoPara', models.IntegerField()),
            ],
        ),
    ]
